/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author Crazzi_Boii
 */
public class GameScreen extends javax.swing.JFrame {

    static int und=0,p=1;
    static int b1,b2,b3,b4,b5,b6,b7,b8,b9;
    static final boolean T=true,F=false;
    final static int player1=1,player2=2;
    String pla1,pla2;
    
    public GameScreen() {
        initComponents();
        System.out.println(PlayerDetails.P1);
        System.out.println(PlayerDetails.P2);
        disp();
        inita();
        this.setLocation(300, 130);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        GameLive = new javax.swing.JPanel();
        Box1 = new javax.swing.JPanel();
        CR1 = new javax.swing.JLabel();
        CIR1 = new javax.swing.JLabel();
        Gpan4 = new javax.swing.JPanel();
        CR4 = new javax.swing.JLabel();
        CIR4 = new javax.swing.JLabel();
        Gpan2 = new javax.swing.JPanel();
        CR2 = new javax.swing.JLabel();
        CIR2 = new javax.swing.JLabel();
        Gpan3 = new javax.swing.JPanel();
        CIR3 = new javax.swing.JLabel();
        CR3 = new javax.swing.JLabel();
        Gpan5 = new javax.swing.JPanel();
        CR5 = new javax.swing.JLabel();
        CIR5 = new javax.swing.JLabel();
        Gpan6 = new javax.swing.JPanel();
        CR6 = new javax.swing.JLabel();
        CIR6 = new javax.swing.JLabel();
        Gpan8 = new javax.swing.JPanel();
        CR8 = new javax.swing.JLabel();
        CIR8 = new javax.swing.JLabel();
        Gpan7 = new javax.swing.JPanel();
        CR7 = new javax.swing.JLabel();
        CIR7 = new javax.swing.JLabel();
        Gpan9 = new javax.swing.JPanel();
        CR9 = new javax.swing.JLabel();
        CIR9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        GamePad1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Bundo = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jUndo2 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jUndo1 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jBPau = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jBRest = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLpl1 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLpl2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setResizable(false);

        GameLive.setBackground(new java.awt.Color(204, 204, 204));
        GameLive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GameLive.setAutoscrolls(true);
        GameLive.setPreferredSize(new java.awt.Dimension(250, 250));

        Box1.setBorder(javax.swing.BorderFactory.createTitledBorder("1"));
        Box1.setMinimumSize(new java.awt.Dimension(70, 70));
        Box1.setPreferredSize(new java.awt.Dimension(70, 70));

        CR1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR1.setText("X");
        CR1.setIconTextGap(0);

        CIR1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR1.setText("O");
        CIR1.setIconTextGap(0);

        javax.swing.GroupLayout Box1Layout = new javax.swing.GroupLayout(Box1);
        Box1.setLayout(Box1Layout);
        Box1Layout.setHorizontalGroup(
            Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Box1Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(CR1)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Box1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(CIR1)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        Box1Layout.setVerticalGroup(
            Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Box1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CR1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Box1Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CIR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        Gpan4.setBorder(javax.swing.BorderFactory.createTitledBorder("4"));
        Gpan4.setMinimumSize(new java.awt.Dimension(70, 70));
        Gpan4.setPreferredSize(new java.awt.Dimension(70, 70));

        CR4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR4.setText("X");
        CR4.setIconTextGap(0);

        CIR4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR4.setText("O");
        CIR4.setIconTextGap(0);

        javax.swing.GroupLayout Gpan4Layout = new javax.swing.GroupLayout(Gpan4);
        Gpan4.setLayout(Gpan4Layout);
        Gpan4Layout.setHorizontalGroup(
            Gpan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan4Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(CIR4)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        Gpan4Layout.setVerticalGroup(
            Gpan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan4Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CIR4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        Gpan2.setBorder(javax.swing.BorderFactory.createTitledBorder("2"));
        Gpan2.setMinimumSize(new java.awt.Dimension(70, 70));
        Gpan2.setPreferredSize(new java.awt.Dimension(70, 70));

        CR2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR2.setText("X");
        CR2.setIconTextGap(0);

        CIR2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR2.setText("O");
        CIR2.setIconTextGap(0);

        javax.swing.GroupLayout Gpan2Layout = new javax.swing.GroupLayout(Gpan2);
        Gpan2.setLayout(Gpan2Layout);
        Gpan2Layout.setHorizontalGroup(
            Gpan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(Gpan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR2)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(CIR2)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        Gpan2Layout.setVerticalGroup(
            Gpan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR2)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan2Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CIR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        Gpan3.setBorder(javax.swing.BorderFactory.createTitledBorder("3"));
        Gpan3.setMinimumSize(new java.awt.Dimension(70, 70));
        Gpan3.setPreferredSize(new java.awt.Dimension(70, 70));

        CIR3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR3.setText("O");
        CIR3.setIconTextGap(0);

        CR3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR3.setText("X");
        CR3.setIconTextGap(0);

        javax.swing.GroupLayout Gpan3Layout = new javax.swing.GroupLayout(Gpan3);
        Gpan3.setLayout(Gpan3Layout);
        Gpan3Layout.setHorizontalGroup(
            Gpan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gpan3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CIR3)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(Gpan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(CR3)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        Gpan3Layout.setVerticalGroup(
            Gpan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gpan3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(CIR3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Gpan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan3Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CR3)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Gpan5.setBorder(javax.swing.BorderFactory.createTitledBorder("5"));
        Gpan5.setMinimumSize(new java.awt.Dimension(70, 70));

        CR5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR5.setText("X");
        CR5.setIconTextGap(0);

        CIR5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR5.setText("O");
        CIR5.setIconTextGap(0);

        javax.swing.GroupLayout Gpan5Layout = new javax.swing.GroupLayout(Gpan5);
        Gpan5.setLayout(Gpan5Layout);
        Gpan5Layout.setHorizontalGroup(
            Gpan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR5)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan5Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(CIR5)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        Gpan5Layout.setVerticalGroup(
            Gpan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR5)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan5Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CIR5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        Gpan6.setBorder(javax.swing.BorderFactory.createTitledBorder("6"));
        Gpan6.setMinimumSize(new java.awt.Dimension(70, 70));
        Gpan6.setPreferredSize(new java.awt.Dimension(70, 70));

        CR6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR6.setText("X");
        CR6.setIconTextGap(0);

        CIR6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR6.setText("O");
        CIR6.setIconTextGap(0);

        javax.swing.GroupLayout Gpan6Layout = new javax.swing.GroupLayout(Gpan6);
        Gpan6.setLayout(Gpan6Layout);
        Gpan6Layout.setHorizontalGroup(
            Gpan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR6)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan6Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(CIR6)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        Gpan6Layout.setVerticalGroup(
            Gpan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR6)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan6Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CIR6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        Gpan8.setBorder(javax.swing.BorderFactory.createTitledBorder("8"));
        Gpan8.setMinimumSize(new java.awt.Dimension(70, 70));
        Gpan8.setPreferredSize(new java.awt.Dimension(70, 70));

        CR8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR8.setText("X");
        CR8.setIconTextGap(0);

        CIR8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR8.setText("O");
        CIR8.setIconTextGap(0);

        javax.swing.GroupLayout Gpan8Layout = new javax.swing.GroupLayout(Gpan8);
        Gpan8.setLayout(Gpan8Layout);
        Gpan8Layout.setHorizontalGroup(
            Gpan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR8)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan8Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(CIR8)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        Gpan8Layout.setVerticalGroup(
            Gpan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR8)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan8Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CIR8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        Gpan7.setBorder(javax.swing.BorderFactory.createTitledBorder("7"));
        Gpan7.setMinimumSize(new java.awt.Dimension(70, 70));

        CR7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR7.setText("X");
        CR7.setIconTextGap(0);

        CIR7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR7.setText("O");
        CIR7.setIconTextGap(0);

        javax.swing.GroupLayout Gpan7Layout = new javax.swing.GroupLayout(Gpan7);
        Gpan7.setLayout(Gpan7Layout);
        Gpan7Layout.setHorizontalGroup(
            Gpan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR7)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan7Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(CIR7)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        Gpan7Layout.setVerticalGroup(
            Gpan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR7)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan7Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CIR7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        Gpan9.setBorder(javax.swing.BorderFactory.createTitledBorder("9"));
        Gpan9.setMinimumSize(new java.awt.Dimension(70, 70));

        CR9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CR9.setText("X");
        CR9.setIconTextGap(0);

        CIR9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CIR9.setText("O");
        CIR9.setIconTextGap(0);

        javax.swing.GroupLayout Gpan9Layout = new javax.swing.GroupLayout(Gpan9);
        Gpan9.setLayout(Gpan9Layout);
        Gpan9Layout.setHorizontalGroup(
            Gpan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR9)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan9Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(CIR9)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        Gpan9Layout.setVerticalGroup(
            Gpan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Gpan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CR9)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(Gpan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Gpan9Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(CIR9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        javax.swing.GroupLayout GameLiveLayout = new javax.swing.GroupLayout(GameLive);
        GameLive.setLayout(GameLiveLayout);
        GameLiveLayout.setHorizontalGroup(
            GameLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameLiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GameLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameLiveLayout.createSequentialGroup()
                        .addGroup(GameLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Gpan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Box1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GameLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GameLiveLayout.createSequentialGroup()
                                .addComponent(Gpan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Gpan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(GameLiveLayout.createSequentialGroup()
                                .addComponent(Gpan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Gpan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(GameLiveLayout.createSequentialGroup()
                        .addComponent(Gpan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gpan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(Gpan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GameLiveLayout.setVerticalGroup(
            GameLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameLiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GameLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Box1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gpan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gpan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GameLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Gpan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gpan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gpan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(GameLiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gpan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gpan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gpan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Score", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(70, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(73, 74));
        jPanel4.setMinimumSize(new java.awt.Dimension(73, 74));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("1");
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMaximumSize(new java.awt.Dimension(73, 74));
        jPanel7.setMinimumSize(new java.awt.Dimension(73, 74));
        jPanel7.setPreferredSize(new java.awt.Dimension(73, 74));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("2");
        jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(73, 74));
        jPanel10.setMinimumSize(new java.awt.Dimension(73, 74));
        jPanel10.setPreferredSize(new java.awt.Dimension(73, 74));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("4");
        jButton4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setMaximumSize(new java.awt.Dimension(73, 74));
        jPanel13.setMinimumSize(new java.awt.Dimension(73, 74));
        jPanel13.setPreferredSize(new java.awt.Dimension(73, 74));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("5");
        jButton5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setMaximumSize(new java.awt.Dimension(73, 74));
        jPanel9.setMinimumSize(new java.awt.Dimension(73, 74));
        jPanel9.setPreferredSize(new java.awt.Dimension(73, 74));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("3");
        jButton3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setMaximumSize(new java.awt.Dimension(73, 74));
        jPanel14.setMinimumSize(new java.awt.Dimension(73, 74));
        jPanel14.setPreferredSize(new java.awt.Dimension(73, 74));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("6");
        jButton6.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setMaximumSize(new java.awt.Dimension(73, 74));
        jPanel17.setMinimumSize(new java.awt.Dimension(73, 74));
        jPanel17.setPreferredSize(new java.awt.Dimension(73, 74));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("7");
        jButton7.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setMaximumSize(new java.awt.Dimension(73, 74));
        jPanel18.setMinimumSize(new java.awt.Dimension(73, 74));
        jPanel18.setPreferredSize(new java.awt.Dimension(73, 74));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("8");
        jButton8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        GamePad1.setBackground(new java.awt.Color(255, 255, 255));
        GamePad1.setMaximumSize(new java.awt.Dimension(73, 74));
        GamePad1.setMinimumSize(new java.awt.Dimension(73, 74));
        GamePad1.setPreferredSize(new java.awt.Dimension(73, 74));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("9");
        jButton9.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GamePad1Layout = new javax.swing.GroupLayout(GamePad1);
        GamePad1.setLayout(GamePad1Layout);
        GamePad1Layout.setHorizontalGroup(
            GamePad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePad1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        GamePad1Layout.setVerticalGroup(
            GamePad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePad1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GamePad1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GamePad1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setPreferredSize(new java.awt.Dimension(150, 95));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(149, 32));
        jPanel6.setMinimumSize(new java.awt.Dimension(149, 32));
        jPanel6.setPreferredSize(new java.awt.Dimension(149, 32));

        Bundo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bundo.setText("UNDO");
        Bundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Bundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bundo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setMaximumSize(new java.awt.Dimension(149, 32));
        jPanel21.setMinimumSize(new java.awt.Dimension(149, 32));
        jPanel21.setPreferredSize(new java.awt.Dimension(149, 32));

        jUndo2.setBackground(new java.awt.Color(255, 255, 255));
        jUndo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jUndo2.setForeground(new java.awt.Color(255, 0, 0));
        jUndo2.setText("No Undo Available");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jUndo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jUndo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setMaximumSize(new java.awt.Dimension(149, 32));
        jPanel22.setMinimumSize(new java.awt.Dimension(149, 32));
        jPanel22.setPreferredSize(new java.awt.Dimension(149, 32));

        jUndo1.setBackground(new java.awt.Color(255, 255, 255));
        jUndo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jUndo1.setForeground(new java.awt.Color(255, 0, 0));
        jUndo1.setText("No Undo Available");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jUndo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jUndo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setPreferredSize(new java.awt.Dimension(150, 95));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel11.setMaximumSize(new java.awt.Dimension(0, 41));
        jPanel11.setMinimumSize(new java.awt.Dimension(0, 41));
        jPanel11.setPreferredSize(new java.awt.Dimension(0, 41));

        jBPau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBPau.setText("Pause");
        jBPau.setMaximumSize(new java.awt.Dimension(83, 25));
        jBPau.setMinimumSize(new java.awt.Dimension(83, 25));
        jBPau.setPreferredSize(new java.awt.Dimension(83, 25));
        jBPau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jBPau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBPau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel12.setMaximumSize(new java.awt.Dimension(0, 41));
        jPanel12.setMinimumSize(new java.awt.Dimension(0, 41));
        jPanel12.setPreferredSize(new java.awt.Dimension(0, 41));

        jBRest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBRest.setText("Restart");
        jBRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jBRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel19.setMaximumSize(new java.awt.Dimension(140, 89));
        jPanel19.setMinimumSize(new java.awt.Dimension(140, 89));
        jPanel19.setPreferredSize(new java.awt.Dimension(140, 89));

        jLpl1.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLpl1.setOpaque(true);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLpl1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLpl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel2.setText("vs");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel23.setMaximumSize(new java.awt.Dimension(140, 89));
        jPanel23.setMinimumSize(new java.awt.Dimension(140, 89));
        jPanel23.setPreferredSize(new java.awt.Dimension(140, 89));

        jLpl2.setFont(new java.awt.Font("Segoe Script", 3, 24)); // NOI18N
        jLpl2.setOpaque(true);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLpl2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLpl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenu1.setIconTextGap(0);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("New Game");
        jMenuItem2.setFocusable(true);
        jMenuItem2.setIconTextGap(0);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Edit Playes Details");
        jMenuItem1.setHideActionText(true);
        jMenuItem1.setIconTextGap(0);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Quit");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem5.setText("jMenuItem5");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem3.setText("Gameplay");
        jMenuItem3.setIconTextGap(0);
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("About");
        jMenuItem4.setIconTextGap(0);
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GameLive, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GameLive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR1.setVisible(T);
            b1=player2;
        }
        else{
            CR1.setVisible(T);
            b1=player1;
        }
        p++;
        und=1;
        gCheck();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BundoActionPerformed
        // TODO add your handling code here:
        undo(und);
    }//GEN-LAST:event_BundoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR2.setVisible(T);
            b2=player2;
        }
        else{
            CR2.setVisible(T);
            b2=player1;
        }
        p++;
        und=2;
        gCheck();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR3.setVisible(T);
            b3=player2;
        }
        else{
            CR3.setVisible(T);
            b3=player1;
        }
        p++;
        und=3;
        gCheck();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR4.setVisible(T);
            b4=player2;
        }
        else{
            CR4.setVisible(T);
            b4=player1;
        }
        p++;
        und=4;
        gCheck();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jButton5.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR5.setVisible(T);
            b5=player2;
        }
        else{
            CR5.setVisible(T);
            b5=player1;
        }
        p++;
        und=5;
        gCheck();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton6.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR6.setVisible(T);
            b6=player2;
        }
        else{
            CR6.setVisible(T);
            b6=player1;
        }
        p++;
        und=6;
        gCheck();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR7.setVisible(T);
            b7=player2;
        }
        else{
            CR7.setVisible(T);
            b7=player1;
        }
        p++;
        und=7;
        gCheck();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton8.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR8.setVisible(T);
            b8=player2;
        }
        else{
            CR8.setVisible(T);
            b8=player1;
        }
        p++;
        und=8;
        gCheck();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jButton9.setVisible(F);
        Bundo.setVisible(T);
        jUndo1.setVisible(F);
        jUndo2.setVisible(F);
        if(p%2==0){
            CIR9.setVisible(T);
            b9=player2;
        }
        else{
            CR9.setVisible(T);
            b9=player1;
        }
        p++;
        und=9;
        gCheck();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jBRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRestActionPerformed
        // TODO add your handling code here:
       new PlayerDetails().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jBRestActionPerformed

    private void jBPauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPauActionPerformed
        // TODO add your handling code here:
        new EditDetails().setVisible(true);
        EditDetails.objCatcher(this);
        this.hide();
    }//GEN-LAST:event_jBPauActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new PlayerDetails().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Box1;
    private javax.swing.JButton Bundo;
    private javax.swing.JLabel CIR1;
    private javax.swing.JLabel CIR2;
    private javax.swing.JLabel CIR3;
    private javax.swing.JLabel CIR4;
    private javax.swing.JLabel CIR5;
    private javax.swing.JLabel CIR6;
    private javax.swing.JLabel CIR7;
    private javax.swing.JLabel CIR8;
    private javax.swing.JLabel CIR9;
    private javax.swing.JLabel CR1;
    private javax.swing.JLabel CR2;
    private javax.swing.JLabel CR3;
    private javax.swing.JLabel CR4;
    private javax.swing.JLabel CR5;
    private javax.swing.JLabel CR6;
    private javax.swing.JLabel CR7;
    private javax.swing.JLabel CR8;
    private javax.swing.JLabel CR9;
    private javax.swing.JPanel GameLive;
    private javax.swing.JPanel GamePad1;
    private javax.swing.JPanel Gpan2;
    private javax.swing.JPanel Gpan3;
    private javax.swing.JPanel Gpan4;
    private javax.swing.JPanel Gpan5;
    private javax.swing.JPanel Gpan6;
    private javax.swing.JPanel Gpan7;
    private javax.swing.JPanel Gpan8;
    private javax.swing.JPanel Gpan9;
    private javax.swing.JButton jBPau;
    private javax.swing.JButton jBRest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLpl1;
    private javax.swing.JLabel jLpl2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jUndo1;
    private javax.swing.JLabel jUndo2;
    // End of variables declaration//GEN-END:variables

private void inita(){
        //boolean f=false;
        CR1.setVisible(F);
        CR4.setVisible(F);
        CR2.setVisible(F);
        CR3.setVisible(F);
        CR5.setVisible(F);
        CR6.setVisible(F);
        CR8.setVisible(F);
        CR7.setVisible(F);
        CR9.setVisible(F);
        CIR1.setVisible(F);
        CIR4.setVisible(F);
        CIR2.setVisible(F);
        CIR3.setVisible(F);
        CIR5.setVisible(F);
        CIR6.setVisible(F);
        CIR8.setVisible(F);
        CIR7.setVisible(F);
        CIR9.setVisible(F);
        Bundo.setVisible(F);
        jUndo1.setVisible(T);
        jUndo2.setVisible(T);
        b1=b2=b3=b4=b5=b6=b7=b8=b9=0;
        und=0;
        p=1;
}
private void undo(int a){
        //boolean f=false;
        Bundo.setVisible(F);
        jUndo1.setVisible(T);
        jUndo2.setVisible(T);
        switch(a){
            case 1:{
                CR1.setVisible(F);
                CIR1.setVisible(F);
                jButton1.setVisible(T);
                b1=0;
                p--;
                break;
            }
            case 2:{
                CR2.setVisible(F);
                CIR2.setVisible(F);
                jButton2.setVisible(T);
                b2=0;
                p--;
                break;}
            case 3:{
                CR3.setVisible(F);
                CIR3.setVisible(F);
                jButton3.setVisible(T);
                b3=0;
                p--;
                break;
            }
            case 4:{
                CR4.setVisible(F);
                CIR4.setVisible(F);
                jButton4.setVisible(T);
                b4=0;
                p--;
                break;
            }
            case 5:{
                CR5.setVisible(F);
                CIR5.setVisible(F);
                jButton5.setVisible(T);
                b5=0;
                p--;
                break;
            }
            case 6:{
                CR6.setVisible(F);
                CIR6.setVisible(F);
                jButton6.setVisible(T);
                b6=0;
                p--;
                break;
            }
            case 7:{
                CR7.setVisible(F);
                CIR7.setVisible(F);
                jButton7.setVisible(T);
                b7=0;
                p--;
                break;
            }
            case 8:{
                CR8.setVisible(F);
                CIR8.setVisible(F);
                jButton8.setVisible(T);
                b8=0;
                p--;
                break;
            }
            case 9:{
                CR9.setVisible(F);
                CIR9.setVisible(F);
                jButton9.setVisible(T);
                b9=0;
                p--;
                break;
            }
        }
    }
private void gCheck(){
    /*System.out.println("b1=" + b1);
    System.out.println("b2=" + b2);
    System.out.println("b3=" + b3);
    System.out.println("b4=" + b4);
    System.out.println("b5=" + b5);
    System.out.println("b6=" + b6);
    System.out.println("b7=" + b7);
    System.out.println("b8=" + b8);
    System.out.println("b9=" + b9);
    System.out.println("---------");*/
    if(b1==b2 && b1==b3){
        if(b1==1 || b1==2){
        new Winnner(b1).setVisible(T);
        this.dispose();
        }
    }else
    if(b4==b5 && b4==b6){
        if(b4==1 || b4==2){
        System.out.println("1");
        new Winnner(b4).setVisible(T);
        this.dispose();
        }
    }else
    if(b7==b8 && b7==b9){
        if(b7==1 || b7==2){
        System.out.println("2");
        new Winnner(b7).setVisible(T);
        this.dispose();
        }
    }else
    if(b1==b4 && b1==b7){
        if(b1==1 || b1==2){
        System.out.println("3");
        new Winnner(b1).setVisible(T);
        this.dispose();
        }
    }else
    if(b2==b5 && b2==b8){
        if(b2==1 || b2==2){
        System.out.println("4");
        new Winnner(b2).setVisible(T);
        this.dispose();
        }
    }else
    if(b3==b6 && b3==b9){
        if(b3==1 || b3==2){
        System.out.println("5");
        new Winnner(b3).setVisible(T);
        this.dispose();
        }
    }else
    if(b1==b5 && b1==b9){
        if(b1==1 || b1==2){
        System.out.println("6");
        new Winnner(b1).setVisible(T);
        this.dispose();
        }
    }else
    if(b3==b5 && b3==b7){
        if(b3==1 || b3==2){
        System.out.println("7");
        new Winnner(b3).setVisible(T);
        this.dispose();
        }
    }else if(p==10){
        new Tie().setVisible(T);
        this.dispose();
    }
}
void disp(){
    pla1=PlayerDetails.P1;
    pla2=PlayerDetails.P2;
    jLpl1.setText(pla1);
    jLpl2.setText(pla2);
}
}
